use techshop;

/*1.	Write an SQL query to find out which customers have not placed any orders. */
select CustomerID, FirstName, LastName, Email, Phone, Address
from Customers where CustomerID not in (select distinct CustomerID from Orders);

/*2.	Write an SQL query to find the total number of products available for sale.  */
select (select count(*) from Products) as TotalProducts;

/*3.	Write an SQL query to calculate the total revenue generated by TechShop.  */
select (select sum(TotalAmount) from Orders) as TotalRevenue;

/*4.	Write an SQL query to calculate the average quantity ordered for products in a specific category. 
Allow users to input the category name as a parameter. */
select ( select avg(O.Quantity) from OrderDetails O 
where O.ProductID in (select ProductID from Products)) as AverageQuantity;

/*5.	Write an SQL query to calculate the total revenue generated by a specific customer. Allow users to input the customer ID as a parameter. */
select (select sum(TotalAmount) from Orders) as TotalRevenue;

/*7.	Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders. */
select c.category_name, sum(od.quantity) as total from orderdetails od
join products p on od.product_id = p.product_id join category c on p.product_id = c.product_id
group by c.category_name order by total desc limit 1;

/*8.	Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending. */
select c.firstname, c.lastname, sum(o.totalamount) as total from customers c
join orders o on c.Customer_id = o.customer_id group by c.customer_id order by total desc;

/*9.	Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers. */
select (select sum(TotalAmount) from Orders)/(select count(*) from Orders) as AverageOrderValue;

/*10.	Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count. */
select C.FirstName, C.LastName, (select count(*) from Orders O 
where O.CustomerID = C.CustomerID) as OrderCount from Customers C;


