use techshop;

/*1.	Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order. */
select O.OrderID, O.OrderDate, O.TotalAmount, C.FirstName, C.LastName, C.Email, C.Phone, C.Address
from Orders O join Customers C on O.CustomerID = C.CustomerID;

/*2.	Write an SQL query to find the total revenue generated by each electronic gadget product. 
Include the product name and the total revenue. */
select P.ProductName, SUM(OD.Quantity * P.Price) as TotalRevenue from OrderDetails OD
join Products P on OD.ProductID = P.ProductID group by P.ProductName order by TotalRevenue desc;

/*3.	Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information. */
select distinct C.CustomerID, C.FirstName, C.LastName, C.Email, C.Phone, C.Address from Customers C
join Orders O on C.CustomerID = O.CustomerID;

/*4.	Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered. */
select P.ProductName, SUM(OD.Quantity) as TotalQuantityOrdered from OrderDetails OD
join Products P on OD.ProductID = P.ProductID
group by P.ProductName order by TotalQuantityOrdered desc limit 1;

/*5.	Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories. */
select ProductName from Products;

/*6.	Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value. */
select C.CustomerID, C.FirstName, C.LastName, avg(O.TotalAmount) as AverageOrderValue
from Customers C join Orders O on C.CustomerID = O.CustomerID
group by C.CustomerID, C.FirstName, C.LastName
order by AverageOrderValue desc;

/*7.	Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue. */
select C.CustomerID, C.FirstName, C.LastName, avg(O.TotalAmount) as AverageOrderValue
from Customers C join Orders O on C.CustomerID = O.CustomerID
group by C.CustomerID, C.FirstName, C.LastName
order by AverageOrderValue desc;

/*8.	Write an SQL query to list electronic gadgets and the number of times each product has been ordered. */
select P.ProductName, COUNT(OD.OrderDetailID) as OrderCount
from OrderDetails OD join Products P on OD.ProductID = P.ProductID
group by P.ProductName
order by OrderCount desc;

/*9.	Write an SQL query to find customers who have purchased a specific electronic gadget product. 
Allow users to input the product name as a parameter. */
select distinct C.CustomerID, C.FirstName, C.LastName, C.Email, C.Phone, C.Address
from Customers C join Orders O on C.CustomerID = O.CustomerID
join OrderDetails OD on O.OrderID = OD.OrderID
join Products P on OD.ProductID = P.ProductID
where P.ProductName = @ProductName;

/*10.	Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters. */
select SUM(TotalAmount) as TotalRevenue from Orders where OrderDate between '2022-01-01' and '2024-07-30';




